-- 문제 5. 월 총매출 조회

SELECT FP.PRODUCT_ID, 
       FP.PRODUCT_NAME, 
       SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES -- 총매출 합 구하기
FROM FOOD_PRODUCT AS FP
JOIN FOOD_ORDER AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%' -- '22년5월' 조회 (날짜 데이터 형식이 YYYY-MM-DD로 통일되었다는 전제하에)
GROUP BY FP.PRODUCT_ID -- uniqueKey 같은 PRODUCT_ID로 그룹화
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC; -- TOTAL_SALES 내림차순 우선 적용 후 PRODUCT_ID 오름차순 적용